### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by muhammad-farhadi** [MIvanovska/Y-GAN#1]
Hello 
I am trying to run your code, but I encountered this error 

```Traceback (most recent call last):
  File "D:\Programs\Mohammad\train.py", line 14, in <module>
    main()
  File "D:\Programs\Mohammad\train.py", line 11, in main
    _=model.train()
  File "D:\Programs\Mohammad\lib\models\y_gan.py", line 273, in train
    self.optimize_params()
  File "D:\Programs\Mohammad\lib\models\y_gan.py", line 212, in optimize_params
    self.backward_g()
  File "D:\Programs\Mohammad\lib\models\y_gan.py", line 151, in backward_g
    self.err_g.backward(retain_graph=True)
  File "D:\Programs\Mohammad\venv\lib\site-packages\torch\_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "D:\Programs\Mohammad\venv\lib\site-packages\torch\autograd\__init__.py", line 147, in backward
    Variable._execution_engine.run_backward(
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.````


Can you help me fix it?
List of packages I use 
(venv) D:\Programs\Mohammad>pip list

```Package Version
----------------- ------------
colorama 0.4.6
joblib 1.4.2
numpy 1.26.4
pillow 10.3.0
pip 24.0
scikit-learn 0.24.2
scipy 1.13.1
setuptools 69.5.1
threadpoolctl 3.5.0
torch 1.9.1+cu111
torchaudio 0.9.1
torchvision 0.10.1+cu111
tqdm 4.64.1
typing_extensions 4.12.1
wheel 0.43.0```

**Comment by MIvanovska** [comment]
Hi,

it sounds like an issue with your CUDA device, which is causing a device-side assertion to fail. As suggested by the error message, try setting CUDA_LAUNCH_BLOCKING=1 to get a more accurate stack trace.

**Comment by muhammad-farhadi** [comment]
thanks but now i want to train in my database and image size is 256*256
the error like this 
Traceback (most recent call last):                                                                                                                                                                                                 
  File "C:\Users\Salvador\Desktop\Y-GAN-cuda11.1\Y-GAN-main\train.py", line 18, in <module>
    main()
  File "C:\Users\Salvador\Desktop\Y-GAN-cuda11.1\Y-GAN-main\train.py", line 14, in main
    _ = model.train()
  File "C:\Users\Salvador\Desktop\Y-GAN-cuda11.1\Y-GAN-main\lib\models\y_gan.py", line 286, in train
    self.optimize_params()
  File "C:\Users\Salvador\Desktop\Y-GAN-cuda11.1\Y-GAN-main\lib\models\y_gan.py", line 214, in optimize_params
    self.forward_g(alpha=self.alpha)
  File "C:\Users\Salvador\Desktop\Y-GAN-cuda11.1\Y-GAN-main\lib\models\y_gan.py", line 114, in forward_g
    _, _, latent_zs_of_permuted_samples, _, _, _ = self.netg(self.latent_zs.detach(),
  File "C:\Users\Salvador\Desktop\Y-GAN-main\.venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\Salvador\Desktop\Y-GAN-main\.venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Salvador\Desktop\Y-GAN-cuda11.1\Y-GAN-main\lib\models\networks.py", line 344, in forward
    latent_zs_of_permuted_samples = self.encoderShape(AA)
  File "C:\Users\Salvador\Desktop\Y-GAN-main\.venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\Salvador\Desktop\Y-GAN-main\.venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Salvador\Desktop\Y-GAN-cuda11.1\Y-GAN-main\lib\models\networks.py", line 131, in forward
    output = self.main(input)
  File "C:\Users\Salvador\Desktop\Y-GAN-main\.venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\Salvador\Desktop\Y-GAN-main\.venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Salvador\Desktop\Y-GAN-main\.venv\lib\site-packages\torch\nn\modules\container.py", line 217, in forward
    input = module(input)
  File "C:\Users\Salvador\Desktop\Y-GAN-main\.venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\Salvador\Desktop\Y-GAN-main\.venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Salvador\Desktop\Y-GAN-main\.venv\lib\site-packages\torch\nn\modules\conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\Salvador\Desktop\Y-GAN-main\.venv\lib\site-packages\torch\nn\modules\conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Calculated padded input size per channel: (3 x 3). Kernel size: (4 x 4). Kernel size can't be greater than actual input size

how to fix it !

**Comment by muhammad-farhadi** [comment]
> Hi,
> 
> it sounds like an issue with your CUDA device, which is causing a device-side assertion to fail. As suggested by the error message, try setting CUDA_LAUNCH_BLOCKING=1 to get a more accurate stack trace.

run code by this command 

python train.py --dataroot data --dataset PIECE --name 15epochs --isize 256 --batchsize 64


but when i set image size to 16 its ok and work fine 
for image size bigger than 32 have this problem

**Comment by LeeHaoRanRan** [comment]
> 谢谢，但现在我想在我的数据库中进行训练，图像大小为 256*256 这样的错误回溯（最近调用最后）：文件“C：\Users\Salvador\Desktop\Y-GAN-cuda11.1\Y-GAN-main\train.py”，第 18 行，在 main（） 文件中“C：\Users\Salvador\Desktop\Y-GAN-cuda11.1\Y-GAN-main\train.py”，第 14 行，在 main _ = model.train（） 文件中 “C：\Users\Salvador\Desktop\Y-GAN-cuda11.1\Y-GAN-main\lib\models\y_gan.py”， 第 286 行，在火车 self.optimize_params（） 文件中 “C：\Users\Salvador\Desktop\Y-GAN-cuda11.1\Y-GAN-main\lib\models\y_gan.py”，第 214 行，在optimize_params self.forward_g（alpha=self.alpha） 文件中 “C：\Users\Salvador\Desktop\Y-GAN-cuda11.1\Y-GAN-main\lib\models\y_gan.py”，第 114 行，forward_g _， _， latent_zs_of_permuted_samples， _， _， _ = self.netg（self.latent_zs.detach（），文件“C：\Users\Salvador\Desktop\Y-GAN-main.venv\lib\site-packages\torch\nn\modules\module.py”，第 1532 行，_wrapped_call_impl返回self._call_impl（*args， **kwargs）文件“C：\Users\Salvador\Desktop\Y-GAN-main.venv\lib\site-packages\torch\nn\modules\module.py”，第 1541 行，_call_impl返回forward_call（*args， **kwargs） 文件“C：\Users\Salvador\Desktop\Y-GAN-cuda11.1\Y-GAN-main\lib\models\networks.py”， 第 344 行，在正向latent_zs_of_permuted_samples = self.encoderShape（AA） 文件中 “C：\Users\Salvador\Desktop\Y-GAN-main.venv\lib\site-packages\torch\nn\modules\module.py”，第 1532 行，_wrapped_call_impl返回 self._call_impl（*args， **kwargs） 文件 “C：\Users\Salvador\Desktop\Y-GAN-main.venv\lib\site-packages\torch\nn\modules\module.py”，第 1541 行，_call_impl返回 forward_call（*args， **kwargs） 文件 “C：\Users\Salvador\Desktop\Y-GAN-cuda11.1\Y-GAN-main\lib\models\networks.py”，第 131 行，在正向输出 = self.main（输入） 文件 “C：\Users\Salvador\Desktop\Y-GAN-main.venv\lib\site-packages\torch\nn\modules\module.py”，第 1532 行，_wrapped_call_impl返回 self._call_impl（*args， **kwargs） 文件 “C：\Users\Salvador\Desktop\Y-GAN-main.venv\lib\site-packages\torch\nn\modules\module.py”，第 1541 行，_call_impl返回 forward_call（*args， **kwargs） 文件“C：\Users\Salvador\Desktop\Y-GAN-main.venv\lib\site-packages\torch\nn\modules\container.py”，第 217 行，在前向输入 = module（input） 文件中“C：\Users\Salvador\Desktop\Y-GAN-main.venv\lib\site-packages\torch\nn\modules\module.py”，第 1532 行，_wrapped_call_impl返回self._call_impl（*args， **kwargs）文件“C：\Users\Salvador\Desktop\Y-GAN-main.venv\lib\site-packages\torch\nn\modules\module.py”，第 1541 行，_call_impl返回forward_call（*args， **kwargs）文件“C：\Users\Salvador\Desktop\Y-GAN-main.venv\lib\site-packages\torch\nn\modules\conv.py”，第 460 行，正向返回self._conv_forward（input， self.weight， self.bias） 文件“C：\Users\Salvador\Desktop\Y-GAN-main.venv\lib\site-packages\torch\nn\modules\conv.py“，第 456 行，_conv_forward返回 F.conv2d（input， weight， bias， self.stride， RuntimeError： 计算的每个通道的填充输入大小：（3 x 3）。内核大小：（4 x 4）。内核大小不能大于实际输入大小
> 
> 怎么修 ！

How did this work out
